baseURL = "https://kkshmz.github.io/"
relativeURLs = "true"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "Origami"
publishDir = "public"
[taxonomies]
  category = "categories"
  tag = "tags"