BaseURL = "https://kkshmz.github.io"
relativeURLs = "true"
languageCode = "en-us"
title = "Kye 'kkshmz' Shimizu"
theme = "Origami"
publishDir = "public"
[taxonomies]
  category = "categories"
  tag = "tags"
paginate = 1
[languages]
  [languages.en]
    title = "Kye 'kkshmz' Shimizu"